import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const brands = ["Square", "Beximco", "Incepta", "Renata", "ACI", "SK+F", "Opsonin", "Healthcare", "Aristopharma", "Beacon", "Orion", "Popular", "General", "Radiant", "Drug Int'l", "UniMed", "Globe", "BioPharma", "PharmaCare", "Ziska"];
const manufacturers = ["Square Pharmaceuticals", "Beximco Pharmaceuticals", "Incepta Pharmaceuticals", "Renata Limited", "ACI Limited", "Eskayef Pharmaceuticals", "Opsonin Pharma", "Healthcare Pharmaceuticals", "Aristopharma Ltd", "Beacon Pharmaceuticals", "Orion Pharma", "Popular Pharmaceuticals", "General Pharmaceuticals", "Radiant Pharmaceuticals", "Drug International"];

const medicines = [
  // CORE ESSENTIALS (150+)
  { name: "Paracetamol", strength: "500mg", category: "Tablet" },
  { name: "Paracetamol", strength: "650mg", category: "Tablet" },
  { name: "Paracetamol ER", strength: "665mg", category: "Tablet" },
  { name: "Paracetamol Syrup", strength: "120mg/5ml", category: "Syrup" },
  { name: "Paracetamol DS Syrup", strength: "250mg/5ml", category: "Syrup" },
  { name: "Paracetamol Drop", strength: "100mg/ml", category: "Drops" },
  { name: "Paracetamol Suppository", strength: "80mg", category: "Suppository" },
  { name: "Ibuprofen", strength: "400mg", category: "Tablet" },
  { name: "Ibuprofen", strength: "200mg", category: "Tablet" },
  { name: "Ibuprofen Suspension", strength: "100mg/5ml", category: "Syrup" },
  { name: "Diclofenac Sodium", strength: "50mg", category: "Tablet" },
  { name: "Diclofenac SR", strength: "100mg", category: "Tablet" },
  { name: "Diclofenac Injection", strength: "75mg/3ml", category: "Injection" },
  { name: "Aceclofenac", strength: "100mg", category: "Tablet" },
  { name: "Aceclofenac SR", strength: "200mg", category: "Tablet" },
  { name: "Naproxen", strength: "500mg", category: "Tablet" },
  { name: "Naproxen", strength: "250mg", category: "Tablet" },
  { name: "Ketorolac", strength: "10mg", category: "Tablet" },
  { name: "Ketorolac Injection", strength: "30mg/ml", category: "Injection" },
  { name: "Etoricoxib", strength: "90mg", category: "Tablet" },
  { name: "Etoricoxib", strength: "60mg", category: "Tablet" },
  { name: "Celecoxib", strength: "200mg", category: "Capsule" },
  { name: "Tramadol", strength: "50mg", category: "Capsule" },
  { name: "Tramadol Injection", strength: "50mg/ml", category: "Injection" },
  { name: "Aspirin", strength: "75mg", category: "Tablet" },
  { name: "Aspirin", strength: "150mg", category: "Tablet" },
  { name: "Aspirin", strength: "300mg", category: "Tablet" },
  
  { name: "Omeprazole", strength: "20mg", category: "Capsule" },
  { name: "Omeprazole", strength: "40mg", category: "Capsule" },
  { name: "Esomeprazole", strength: "20mg", category: "Capsule" },
  { name: "Esomeprazole", strength: "40mg", category: "Capsule" },
  { name: "Pantoprazole", strength: "20mg", category: "Tablet" },
  { name: "Pantoprazole", strength: "40mg", category: "Tablet" },
  { name: "Rabeprazole", strength: "20mg", category: "Tablet" },
  { name: "Lansoprazole", strength: "30mg", category: "Capsule" },
  { name: "Ranitidine", strength: "150mg", category: "Tablet" },
  { name: "Ranitidine", strength: "300mg", category: "Tablet" },
  { name: "Famotidine", strength: "20mg", category: "Tablet" },
  { name: "Famotidine", strength: "40mg", category: "Tablet" },
  { name: "Sucralfate", strength: "500mg", category: "Tablet" },
  { name: "Sucralfate Suspension", strength: "1g/10ml", category: "Suspension" },
  { name: "Domperidone", strength: "10mg", category: "Tablet" },
  { name: "Domperidone Suspension", strength: "5mg/5ml", category: "Syrup" },
  { name: "Ondansetron", strength: "4mg", category: "Tablet" },
  { name: "Ondansetron", strength: "8mg", category: "Tablet" },
  { name: "Ondansetron Injection", strength: "4mg/2ml", category: "Injection" },
  { name: "Metoclopramide", strength: "10mg", category: "Tablet" },
  { name: "Hyoscine Butylbromide", strength: "10mg", category: "Tablet" },
  { name: "Antacid Suspension", strength: "200ml", category: "Suspension" },
  { name: "ORS", strength: "Sachet", category: "Powder" },
  
  { name: "Cetirizine", strength: "10mg", category: "Tablet" },
  { name: "Cetirizine Syrup", strength: "5mg/5ml", category: "Syrup" },
  { name: "Levocetirizine", strength: "5mg", category: "Tablet" },
  { name: "Loratadine", strength: "10mg", category: "Tablet" },
  { name: "Desloratadine", strength: "5mg", category: "Tablet" },
  { name: "Fexofenadine", strength: "120mg", category: "Tablet" },
  { name: "Fexofenadine", strength: "180mg", category: "Tablet" },
  { name: "Rupatadine", strength: "10mg", category: "Tablet" },
  { name: "Bilastine", strength: "20mg", category: "Tablet" },
  { name: "Chlorpheniramine", strength: "4mg", category: "Tablet" },
  { name: "Diphenhydramine", strength: "25mg", category: "Capsule" },
  { name: "Hydroxyzine", strength: "25mg", category: "Tablet" },
  { name: "Montelukast", strength: "4mg", category: "Tablet" },
  { name: "Montelukast", strength: "5mg", category: "Tablet" },
  { name: "Montelukast", strength: "10mg", category: "Tablet" },
  { name: "Montelukast + Levocetirizine", strength: "10mg+5mg", category: "Tablet" },
  { name: "Ketotifen", strength: "1mg", category: "Tablet" },
  
  { name: "Amoxicillin", strength: "250mg", category: "Capsule" },
  { name: "Amoxicillin", strength: "500mg", category: "Capsule" },
  { name: "Amoxicillin Suspension", strength: "125mg/5ml", category: "Syrup" },
  { name: "Amoxicillin DS Suspension", strength: "250mg/5ml", category: "Syrup" },
  { name: "Amoxicillin + Clavulanate", strength: "500mg+125mg", category: "Tablet" },
  { name: "Amoxicillin + Clavulanate", strength: "875mg+125mg", category: "Tablet" },
  { name: "Ampicillin", strength: "500mg", category: "Capsule" },
  { name: "Azithromycin", strength: "250mg", category: "Tablet" },
  { name: "Azithromycin", strength: "500mg", category: "Tablet" },
  { name: "Azithromycin Suspension", strength: "200mg/5ml", category: "Syrup" },
  { name: "Clarithromycin", strength: "250mg", category: "Tablet" },
  { name: "Clarithromycin", strength: "500mg", category: "Tablet" },
  { name: "Erythromycin", strength: "250mg", category: "Tablet" },
  { name: "Erythromycin", strength: "500mg", category: "Tablet" },
  { name: "Cefixime", strength: "200mg", category: "Capsule" },
  { name: "Cefixime", strength: "400mg", category: "Capsule" },
  { name: "Cefixime Suspension", strength: "100mg/5ml", category: "Syrup" },
  { name: "Cefuroxime", strength: "250mg", category: "Tablet" },
  { name: "Cefuroxime", strength: "500mg", category: "Tablet" },
  { name: "Cefuroxime Suspension", strength: "125mg/5ml", category: "Syrup" },
  { name: "Ceftriaxone Injection", strength: "500mg", category: "Injection" },
  { name: "Ceftriaxone Injection", strength: "1g", category: "Injection" },
  { name: "Cefotaxime Injection", strength: "500mg", category: "Injection" },
  { name: "Cefepime Injection", strength: "1g", category: "Injection" },
  { name: "Cephalexin", strength: "250mg", category: "Capsule" },
  { name: "Cephalexin", strength: "500mg", category: "Capsule" },
  { name: "Ciprofloxacin", strength: "250mg", category: "Tablet" },
  { name: "Ciprofloxacin", strength: "500mg", category: "Tablet" },
  { name: "Ciprofloxacin Injection", strength: "200mg/100ml", category: "Injection" },
  { name: "Levofloxacin", strength: "250mg", category: "Tablet" },
  { name: "Levofloxacin", strength: "500mg", category: "Tablet" },
  { name: "Moxifloxacin", strength: "400mg", category: "Tablet" },
  { name: "Ofloxacin", strength: "200mg", category: "Tablet" },
  { name: "Metronidazole", strength: "200mg", category: "Tablet" },
  { name: "Metronidazole", strength: "400mg", category: "Tablet" },
  { name: "Metronidazole Suspension", strength: "200mg/5ml", category: "Syrup" },
  { name: "Tinidazole", strength: "500mg", category: "Tablet" },
  { name: "Doxycycline", strength: "100mg", category: "Capsule" },
  { name: "Tetracycline", strength: "250mg", category: "Capsule" },
  { name: "Cotrimoxazole", strength: "480mg", category: "Tablet" },
  { name: "Cotrimoxazole", strength: "960mg", category: "Tablet" },
  { name: "Cotrimoxazole Suspension", strength: "200mg+40mg/5ml", category: "Syrup" },
  { name: "Flucloxacillin", strength: "250mg", category: "Capsule" },
  { name: "Flucloxacillin", strength: "500mg", category: "Capsule" },
  { name: "Cloxacillin", strength: "500mg", category: "Capsule" },
  { name: "Gentamicin Injection", strength: "80mg/2ml", category: "Injection" },
  { name: "Amikacin Injection", strength: "500mg/2ml", category: "Injection" },
  { name: "Vancomycin Injection", strength: "500mg", category: "Injection" },
  { name: "Meropenem Injection", strength: "1g", category: "Injection" },
  { name: "Imipenem Injection", strength: "500mg", category: "Injection" },
  
  { name: "Amlodipine", strength: "2.5mg", category: "Tablet" },
  { name: "Amlodipine", strength: "5mg", category: "Tablet" },
  { name: "Amlodipine", strength: "10mg", category: "Tablet" },
  { name: "Nifedipine", strength: "10mg", category: "Capsule" },
  { name: "Nifedipine SR", strength: "20mg", category: "Tablet" },
  { name: "Losartan", strength: "25mg", category: "Tablet" },
  { name: "Losartan", strength: "50mg", category: "Tablet" },
  { name: "Losartan + HCTZ", strength: "50mg+12.5mg", category: "Tablet" },
  { name: "Valsartan", strength: "40mg", category: "Tablet" },
  { name: "Valsartan", strength: "80mg", category: "Tablet" },
  { name: "Valsartan", strength: "160mg", category: "Tablet" },
  { name: "Telmisartan", strength: "20mg", category: "Tablet" },
  { name: "Telmisartan", strength: "40mg", category: "Tablet" },
  { name: "Telmisartan", strength: "80mg", category: "Tablet" },
  { name: "Olmesartan", strength: "20mg", category: "Tablet" },
  { name: "Olmesartan", strength: "40mg", category: "Tablet" },
  { name: "Candesartan", strength: "8mg", category: "Tablet" },
  { name: "Enalapril", strength: "5mg", category: "Tablet" },
  { name: "Enalapril", strength: "10mg", category: "Tablet" },
  { name: "Ramipril", strength: "2.5mg", category: "Tablet" },
  { name: "Ramipril", strength: "5mg", category: "Tablet" },
  { name: "Lisinopril", strength: "5mg", category: "Tablet" },
  { name: "Bisoprolol", strength: "2.5mg", category: "Tablet" },
  { name: "Bisoprolol", strength: "5mg", category: "Tablet" },
  { name: "Metoprolol", strength: "25mg", category: "Tablet" },
  { name: "Metoprolol", strength: "50mg", category: "Tablet" },
  { name: "Atenolol", strength: "25mg", category: "Tablet" },
  { name: "Atenolol", strength: "50mg", category: "Tablet" },
  { name: "Carvedilol", strength: "3.125mg", category: "Tablet" },
  { name: "Carvedilol", strength: "6.25mg", category: "Tablet" },
  { name: "Carvedilol", strength: "12.5mg", category: "Tablet" },
  { name: "Propranolol", strength: "10mg", category: "Tablet" },
  { name: "Propranolol", strength: "40mg", category: "Tablet" },
  { name: "Labetalol", strength: "100mg", category: "Tablet" },
  { name: "Atorvastatin", strength: "10mg", category: "Tablet" },
  { name: "Atorvastatin", strength: "20mg", category: "Tablet" },
  { name: "Atorvastatin", strength: "40mg", category: "Tablet" },
  { name: "Rosuvastatin", strength: "5mg", category: "Tablet" },
  { name: "Rosuvastatin", strength: "10mg", category: "Tablet" },
  { name: "Rosuvastatin", strength: "20mg", category: "Tablet" },
  { name: "Simvastatin", strength: "10mg", category: "Tablet" },
  { name: "Simvastatin", strength: "20mg", category: "Tablet" },
  { name: "Clopidogrel", strength: "75mg", category: "Tablet" },
  { name: "Ticagrelor", strength: "90mg", category: "Tablet" },
  { name: "Warfarin", strength: "1mg", category: "Tablet" },
  { name: "Warfarin", strength: "5mg", category: "Tablet" },
  { name: "Furosemide", strength: "20mg", category: "Tablet" },
  { name: "Furosemide", strength: "40mg", category: "Tablet" },
  { name: "Furosemide Injection", strength: "20mg/2ml", category: "Injection" },
  { name: "Spironolactone", strength: "25mg", category: "Tablet" },
  { name: "Spironolactone", strength: "50mg", category: "Tablet" },
  { name: "Hydrochlorothiazide", strength: "25mg", category: "Tablet" },
  { name: "Indapamide", strength: "1.5mg", category: "Tablet" },
  { name: "Digoxin", strength: "0.25mg", category: "Tablet" },
  { name: "Isosorbide Mononitrate", strength: "20mg", category: "Tablet" },
  { name: "Isosorbide Dinitrate", strength: "10mg", category: "Tablet" },
  { name: "Nitroglycerin", strength: "0.5mg", category: "Tablet" },
  { name: "Amiodarone", strength: "200mg", category: "Tablet" },
  
  { name: "Metformin", strength: "500mg", category: "Tablet" },
  { name: "Metformin", strength: "850mg", category: "Tablet" },
  { name: "Metformin", strength: "1000mg", category: "Tablet" },
  { name: "Metformin SR", strength: "500mg", category: "Tablet" },
  { name: "Glimepiride", strength: "1mg", category: "Tablet" },
  { name: "Glimepiride", strength: "2mg", category: "Tablet" },
  { name: "Glimepiride", strength: "4mg", category: "Tablet" },
  { name: "Gliclazide", strength: "40mg", category: "Tablet" },
  { name: "Gliclazide", strength: "80mg", category: "Tablet" },
  { name: "Glipizide", strength: "5mg", category: "Tablet" },
  { name: "Sitagliptin", strength: "50mg", category: "Tablet" },
  { name: "Sitagliptin", strength: "100mg", category: "Tablet" },
  { name: "Vildagliptin", strength: "50mg", category: "Tablet" },
  { name: "Saxagliptin", strength: "5mg", category: "Tablet" },
  { name: "Empagliflozin", strength: "10mg", category: "Tablet" },
  { name: "Empagliflozin", strength: "25mg", category: "Tablet" },
  { name: "Dapagliflozin", strength: "10mg", category: "Tablet" },
  { name: "Pioglitazone", strength: "15mg", category: "Tablet" },
  { name: "Pioglitazone", strength: "30mg", category: "Tablet" },
  { name: "Insulin Regular", strength: "100 IU/ml", category: "Injection" },
  { name: "Insulin NPH", strength: "100 IU/ml", category: "Injection" },
  { name: "Insulin 30/70", strength: "100 IU/ml", category: "Injection" },
  { name: "Insulin Glargine", strength: "100 IU/ml", category: "Injection" },
  { name: "Insulin Aspart", strength: "100 IU/ml", category: "Injection" },
  { name: "Insulin Lispro", strength: "100 IU/ml", category: "Injection" },
  
  // Respiratory
  { name: "Salbutamol Inhaler", strength: "100mcg", category: "Inhaler" },
  { name: "Salbutamol Tablet", strength: "2mg", category: "Tablet" },
  { name: "Salbutamol Tablet", strength: "4mg", category: "Tablet" },
  { name: "Salbutamol Syrup", strength: "2mg/5ml", category: "Syrup" },
  { name: "Salbutamol Nebulizer", strength: "5mg/ml", category: "Nebulizer" },
  { name: "Bambuterol", strength: "10mg", category: "Tablet" },
  { name: "Bambuterol Syrup", strength: "1mg/5ml", category: "Syrup" },
  { name: "Levosalbutamol", strength: "1mg", category: "Tablet" },
  { name: "Terbutaline", strength: "2.5mg", category: "Tablet" },
  { name: "Theophylline", strength: "100mg", category: "Tablet" },
  { name: "Theophylline", strength: "200mg", category: "Tablet" },
  { name: "Doxofylline", strength: "400mg", category: "Tablet" },
  { name: "Prednisolone", strength: "5mg", category: "Tablet" },
  { name: "Prednisolone", strength: "10mg", category: "Tablet" },
  { name: "Prednisolone", strength: "20mg", category: "Tablet" },
  { name: "Dexamethasone", strength: "0.5mg", category: "Tablet" },
  { name: "Dexamethasone Injection", strength: "4mg/ml", category: "Injection" },
  { name: "Budesonide Inhaler", strength: "200mcg", category: "Inhaler" },
  { name: "Budesonide + Formoterol", strength: "160/4.5mcg", category: "Inhaler" },
  { name: "Fluticasone Inhaler", strength: "125mcg", category: "Inhaler" },
  { name: "Salmeterol + Fluticasone", strength: "25/125mcg", category: "Inhaler" },
  { name: "Montelukast Paediatric", strength: "4mg", category: "Tablet" },
  { name: "Acetylcysteine", strength: "600mg", category: "Tablet" },
  { name: "Bromhexine", strength: "8mg", category: "Tablet" },
  { name: "Ambroxol", strength: "30mg", category: "Tablet" },
  { name: "Guaifenesin", strength: "100mg/5ml", category: "Syrup" },
  { name: "Dextromethorphan", strength: "10mg/5ml", category: "Syrup" },
  
  // Neuro
  { name: "Carbamazepine", strength: "100mg", category: "Tablet" },
  { name: "Carbamazepine", strength: "200mg", category: "Tablet" },
  { name: "Sodium Valproate", strength: "200mg", category: "Tablet" },
  { name: "Sodium Valproate", strength: "500mg", category: "Tablet" },
  { name: "Phenytoin", strength: "50mg", category: "Tablet" },
  { name: "Phenytoin", strength: "100mg", category: "Tablet" },
  { name: "Phenobarbitone", strength: "30mg", category: "Tablet" },
  { name: "Levetiracetam", strength: "250mg", category: "Tablet" },
  { name: "Levetiracetam", strength: "500mg", category: "Tablet" },
  { name: "Topiramate", strength: "25mg", category: "Tablet" },
  { name: "Lamotrigine", strength: "25mg", category: "Tablet" },
  { name: "Gabapentin", strength: "100mg", category: "Capsule" },
  { name: "Pregabalin", strength: "75mg", category: "Capsule" },
  { name: "Amitriptyline", strength: "10mg", category: "Tablet" },
  { name: "Amitriptyline", strength: "25mg", category: "Tablet" },
  { name: "Imipramine", strength: "25mg", category: "Tablet" },
  { name: "Fluoxetine", strength: "20mg", category: "Capsule" },
  { name: "Sertraline", strength: "50mg", category: "Tablet" },
  { name: "Escitalopram", strength: "5mg", category: "Tablet" },
  { name: "Escitalopram", strength: "10mg", category: "Tablet" },
  { name: "Paroxetine", strength: "20mg", category: "Tablet" },
  { name: "Risperidone", strength: "1mg", category: "Tablet" },
  { name: "Risperidone", strength: "2mg", category: "Tablet" },
  { name: "Olanzapine", strength: "5mg", category: "Tablet" },
  { name: "Olanzapine", strength: "10mg", category: "Tablet" },
  { name: "Quetiapine", strength: "25mg", category: "Tablet" },
  { name: "Haloperidol", strength: "5mg", category: "Tablet" },
  { name: "Clonazepam", strength: "0.5mg", category: "Tablet" },
  { name: "Clonazepam", strength: "2mg", category: "Tablet" },
  { name: "Diazepam", strength: "5mg", category: "Tablet" },
  { name: "Alprazolam", strength: "0.25mg", category: "Tablet" },
  { name: "Alprazolam", strength: "0.5mg", category: "Tablet" },
  { name: "Lorazepam", strength: "1mg", category: "Tablet" },
  { name: "Zopiclone", strength: "7.5mg", category: "Tablet" },
  { name: "Donepezil", strength: "5mg", category: "Tablet" },
  { name: "Levodopa + Carbidopa", strength: "100mg+10mg", category: "Tablet" },
  
  // Vitamins & Minerals
  { name: "Vitamin A", strength: "200000 IU", category: "Capsule" },
  { name: "Vitamin B Complex", strength: "Complex", category: "Tablet" },
  { name: "Vitamin B1", strength: "100mg", category: "Tablet" },
  { name: "Vitamin B6", strength: "50mg", category: "Tablet" },
  { name: "Vitamin B12", strength: "500mcg", category: "Tablet" },
  { name: "Vitamin B12 Injection", strength: "1000mcg", category: "Injection" },
  { name: "Vitamin C", strength: "250mg", category: "Tablet" },
  { name: "Vitamin C", strength: "500mg", category: "Tablet" },
  { name: "Vitamin C", strength: "1000mg", category: "Tablet" },
  { name: "Vitamin C Chewable", strength: "100mg", category: "Tablet" },
  { name: "Vitamin D3", strength: "1000 IU", category: "Tablet" },
  { name: "Vitamin D3", strength: "2000 IU", category: "Tablet" },
  { name: "Vitamin D3", strength: "4000 IU", category: "Tablet" },
  { name: "Vitamin E", strength: "200 IU", category: "Capsule" },
  { name: "Vitamin E", strength: "400 IU", category: "Capsule" },
  { name: "Vitamin K", strength: "10mg", category: "Injection" },
  { name: "Multivitamin", strength: "Complex", category: "Tablet" },
  { name: "Multivitamin Syrup", strength: "Complex", category: "Syrup" },
  { name: "Multivitamin + Mineral", strength: "Complex", category: "Tablet" },
  { name: "Calcium Carbonate", strength: "500mg", category: "Tablet" },
  { name: "Calcium + D3", strength: "500mg+200 IU", category: "Tablet" },
  { name: "Calcium + Magnesium", strength: "Complex", category: "Tablet" },
  { name: "Ferrous Sulfate", strength: "200mg", category: "Tablet" },
  { name: "Ferrous Fumarate", strength: "200mg", category: "Tablet" },
  { name: "Iron Syrup", strength: "200mg/5ml", category: "Syrup" },
  { name: "Zinc Sulfate", strength: "20mg", category: "Tablet" },
  { name: "Zinc Sulfate Syrup", strength: "20mg/5ml", category: "Syrup" },
  { name: "Folic Acid", strength: "5mg", category: "Tablet" },
  { name: "Folic Acid", strength: "0.4mg", category: "Tablet" },
  { name: "Omega-3", strength: "1000mg", category: "Capsule" },
  { name: "Coenzyme Q10", strength: "30mg", category: "Capsule" },
  { name: "Biotin", strength: "5mg", category: "Tablet" },
  { name: "Glucosamine", strength: "500mg", category: "Tablet" },
  { name: "Chondroitin", strength: "400mg", category: "Tablet" },
  
  // Antifungal/Antiviral
  { name: "Fluconazole", strength: "50mg", category: "Capsule" },
  { name: "Fluconazole", strength: "150mg", category: "Capsule" },
  { name: "Itraconazole", strength: "100mg", category: "Capsule" },
  { name: "Ketoconazole", strength: "200mg", category: "Tablet" },
  { name: "Terbinafine", strength: "250mg", category: "Tablet" },
  { name: "Griseofulvin", strength: "250mg", category: "Tablet" },
  { name: "Acyclovir", strength: "200mg", category: "Tablet" },
  { name: "Acyclovir", strength: "400mg", category: "Tablet" },
  { name: "Acyclovir", strength: "800mg", category: "Tablet" },
  { name: "Acyclovir Cream", strength: "5%", category: "Cream" },
  { name: "Valacyclovir", strength: "500mg", category: "Tablet" },
  { name: "Oseltamivir", strength: "75mg", category: "Capsule" },
  
  // Anthelmintic
  { name: "Albendazole", strength: "400mg", category: "Tablet" },
  { name: "Albendazole Suspension", strength: "200mg/5ml", category: "Syrup" },
  { name: "Mebendazole", strength: "100mg", category: "Tablet" },
  { name: "Mebendazole Suspension", strength: "100mg/5ml", category: "Syrup" },
  { name: "Praziquantel", strength: "600mg", category: "Tablet" },
  { name: "Ivermectin", strength: "6mg", category: "Tablet" },
  
  // Thyroid
  { name: "Levothyroxine", strength: "25mcg", category: "Tablet" },
  { name: "Levothyroxine", strength: "50mcg", category: "Tablet" },
  { name: "Levothyroxine", strength: "100mcg", category: "Tablet" },
  { name: "Carbimazole", strength: "5mg", category: "Tablet" },
  { name: "Propylthiouracil", strength: "50mg", category: "Tablet" },
  
  // Topical
  { name: "Betamethasone Cream", strength: "0.1%", category: "Cream" },
  { name: "Hydrocortisone Cream", strength: "1%", category: "Cream" },
  { name: "Clotrimazole Cream", strength: "1%", category: "Cream" },
  { name: "Ketoconazole Cream", strength: "2%", category: "Cream" },
  { name: "Miconazole Cream", strength: "2%", category: "Cream" },
  { name: "Econazole Cream", strength: "1%", category: "Cream" },
  { name: "Mupirocin Ointment", strength: "2%", category: "Ointment" },
  { name: "Fusidic Acid Cream", strength: "2%", category: "Cream" },
  { name: "Silver Sulfadiazine Cream", strength: "1%", category: "Cream" },
  { name: "Permethrin Cream", strength: "5%", category: "Cream" },
  { name: "Calamine Lotion", strength: "Lotion", category: "Lotion" },
  { name: "Crotamiton Cream", strength: "10%", category: "Cream" },
  { name: "Tretinoin Cream", strength: "0.025%", category: "Cream" },
  { name: "Benzoyl Peroxide", strength: "5%", category: "Gel" },
  { name: "Clindamycin Gel", strength: "1%", category: "Gel" },
  { name: "Adapalene Gel", strength: "0.1%", category: "Gel" },
  { name: "Ketoconazole Shampoo", strength: "2%", category: "Shampoo" },
  
  // Eye/Ear/Nasal
  { name: "Ciprofloxacin Eye Drops", strength: "0.3%", category: "Drops" },
  { name: "Moxifloxacin Eye Drops", strength: "0.5%", category: "Drops" },
  { name: "Ofloxacin Eye Drops", strength: "0.3%", category: "Drops" },
  { name: "Tobramycin Eye Drops", strength: "0.3%", category: "Drops" },
  { name: "Chloramphenicol Eye Drops", strength: "0.5%", category: "Drops" },
  { name: "Ketorolac Eye Drops", strength: "0.5%", category: "Drops" },
  { name: "Timolol Eye Drops", strength: "0.5%", category: "Drops" },
  { name: "Latanoprost Eye Drops", strength: "0.005%", category: "Drops" },
  { name: "Brimonidine Eye Drops", strength: "0.2%", category: "Drops" },
  { name: "Dorzolamide Eye Drops", strength: "2%", category: "Drops" },
  { name: "Sodium Chloride Eye Drops", strength: "5%", category: "Drops" },
  { name: "Xylometazoline Nasal Drops", strength: "0.1%", category: "Drops" },
  { name: "Oxymetazoline Nasal Drops", strength: "0.05%", category: "Drops" },
  { name: "Sodium Chloride Nasal Drops", strength: "0.65%", category: "Drops" },
  { name: "Beclomethasone Nasal Spray", strength: "50mcg", category: "Spray" },
  { name: "Fluticasone Nasal Spray", strength: "50mcg", category: "Spray" },
  
  // Others
  { name: "Allopurinol", strength: "100mg", category: "Tablet" },
  { name: "Allopurinol", strength: "300mg", category: "Tablet" },
  { name: "Colchicine", strength: "0.5mg", category: "Tablet" },
  { name: "Febuxostat", strength: "40mg", category: "Tablet" },
  { name: "Febuxostat", strength: "80mg", category: "Tablet" },
  { name: "Finasteride", strength: "1mg", category: "Tablet" },
  { name: "Finasteride", strength: "5mg", category: "Tablet" },
  { name: "Tamsulosin", strength: "0.4mg", category: "Capsule" },
  { name: "Dutasteride", strength: "0.5mg", category: "Capsule" },
  { name: "Sildenafil", strength: "25mg", category: "Tablet" },
  { name: "Sildenafil", strength: "50mg", category: "Tablet" },
  { name: "Sildenafil", strength: "100mg", category: "Tablet" },
  { name: "Tadalafil", strength: "5mg", category: "Tablet" },
  { name: "Tadalafil", strength: "10mg", category: "Tablet" },
  { name: "Tadalafil", strength: "20mg", category: "Tablet" },
  
  // Muscle Relaxants
  { name: "Baclofen", strength: "5mg", category: "Tablet" },
  { name: "Baclofen", strength: "10mg", category: "Tablet" },
  { name: "Tizanidine", strength: "2mg", category: "Tablet" },
  { name: "Tizanidine", strength: "4mg", category: "Tablet" },
  { name: "Chlorzoxazone", strength: "500mg", category: "Tablet" },
  { name: "Orphenadrine", strength: "100mg", category: "Tablet" },
  { name: "Eperisone", strength: "50mg", category: "Tablet" },
  
  // Contraceptive
  { name: "Combined OC Pill", strength: "0.03+0.15mg", category: "Tablet" },
  { name: "Progesterone Only Pill", strength: "0.075mg", category: "Tablet" },
  { name: "Emergency Contraceptive", strength: "1.5mg", category: "Tablet" },
  { name: "Injectable Contraceptive", strength: "150mg/ml", category: "Injection" },
];

async function main() {
  console.log("Starting seed...");
  await prisma.masterMedicine.deleteMany({});
  
  let count = 0;
  let brandIndex = 0;
  let manIndex = 0;

  for (const med of medicines) {
    // প্রতিটি ওষুধ ৩টি ভিন্ন কোম্পানির অধীনে তৈরি হবে
    for (let i = 0; i < 3; i++) {
      const brand = brands[(brandIndex + i) % brands.length];
      const manufacturer = manufacturers[(manIndex + i) % manufacturers.length];
      try {
        await prisma.masterMedicine.create({
          data: {
            name: `${med.name} ${strengthShort(med.strength)}`.trim(),
            brand,
            genericName: med.name,
            strength: med.strength,
            category: med.category,
            manufacturer,
          },
        });
        count++;
      } catch (e) {}
    }
    brandIndex += 3;
    manIndex += 5;
  }
  
  console.log(`✅ ${count} master medicines added to catalog!`);
}

function strengthShort(s: string) {
  if (!s) return "";
  return s.replace(/\s+/g, "");
}

main()
  .catch((e) => console.error(e))
  .finally(() => prisma.$disconnect());
